-- DROP TABLE EDITORA CASCADE CONSTRAINTS;
CREATE TABLE EDITORA(
	COD_EDITORA 	SMALLINT,
	NOME_EDIT 		VARCHAR2(50) NOT NULL,
	END_EDIT		VARCHAR2(100) NOT NULL,
	FONE_EDIT		NUMBER(14) NOT NULL,
	CNPJ_EDIT		NUMBER(14) NOT NULL,
	CONTATO_EDIT	VARCHAR2(50) NOT NULL,
	NACIONALIDADE_EDIT VARCHAR2(30) NOT NULL,
	PRIMARY KEY (COD_EDITORA),
	UNIQUE(CNPJ_EDIT)
);