-- DROP TABLE EMPRESTIMO CASCADE CONSTRAINTS;
CREATE TABLE EMPRESTIMO(
	NUM_EMPRESTIMO INTEGER PRIMARY KEY,
	DT_RETIRADA TIMESTAMP NOT NULL,
	VL_TOTAL_MULTA NUMBER(8,2),
	SITUACAO_EMPRESTIMO CHAR(15) NOT NULL,
	COD_USUARIO INTEGER NOT NULL REFERENCES USUARIO
);

-- DROP SEQUENCE EMPRESTIMO_SEQ;
CREATE SEQUENCE EMPRESTIMO_SEQ START WITH 16000 INCREMENT BY 1;

-- DEFININDO VALORES DEFAULT PARA COLUNAS
ALTER TABLE EMPRESTIMO MODIFY DT_RETIRADA DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE EMPRESTIMO MODIFY VL_TOTAL_MULTA DEFAULT 0.0;


