-- DROP TABLE PROFESSOR CASCADE CONSTRAINTS;
CREATE TABLE PROFESSOR(
	COD_PROF INTEGER NOT NULL,
	COD_FUNCIONAL INTEGER NOT NULL,
	TITULACAO VARCHAR2(30) NOT NULL,
	DATA_ADMISSAO DATE NOT NULL,
	DATA_DESLIGAMENTO DATE,
	PRIMARY KEY (COD_PROF),
	FOREIGN KEY (COD_PROF) REFERENCES USUARIO (COD_USUARIO) ON DELETE CASCADE,
	UNIQUE(COD_FUNCIONAL)
);