CREATE TABLE RESERVA(
	NUM_RESERVA INTEGER PRIMARY KEY,
	DT_RESERVA DATE DEFAULT SYSDATE,
	DT_LIMITE	DATE ,
	SITUACAO_RESERVA VARCHAR2(20) NOT NULL,
	COD_USUARIO INTEGER NOT NULL,
	FOREIGN KEY (COD_USUARIO) REFERENCES PROFESSOR (COD_PROF) ON DELETE CASCADE
);