-- DROP TABLE USUARIO CASCADE CONSTRAINTS;
CREATE TABLE USUARIO (
	COD_USUARIO INTEGER PRIMARY KEY,
	NOME_USUARIO VARCHAR2(75) NOT NULL,
	END_USUARIO VARCHAR2(100) NOT NULL,
	FONE_USUARIO NUMBER(13) NOT NULL,
	EMAIL_USUARIO VARCHAR2(32),
	SEXO_USUARIO CHAR(1) NOT NULL CHECK(SEXO_USUARIO IN ('M','F')),
	DT_NASCIMENTO_USUARIO DATE NOT NULL,
	CPF_USUARIO NUMBER(11) NOT NULL,
	RG_USUARIO CHAR(9) NOT NULL,
	SITUACAO_USUARIO CHAR(15) NOT NULL,
	UNIQUE (CPF_USUARIO)
);

-- ADICIONANDO NOVA COLUNA EM USUARIO
ALTER TABLE USUARIO ADD TIPO_USUARIO CHAR(10) NOT NULL;

-- ADICIONADO CONSTRAINT DE CHECK
ALTER TABLE USUARIO ADD CHECK(TIPO_USUARIO IN ('ALUNO','PROFESSOR','FUNCIONARIO'));

-- ALTERANDO O TAMANHO DE UMA COLUNA
ALTER TABLE USUARIO MODIFY TIPO_USUARIO CHAR(11);

